mia-ajuda/Backend

- docker-compose.yml
- index.js
- src/controllers/HelpController.js
- src/models/Help.js
- src/repository/HelpRepository.js
- src/routes/BaseRoutes.js
- src/routes/HelpRoutes.js
- src/routes/UserRoutes.js
- src/services/HelpService.js
Foram adicionadas rotas para criar, pegar pelo id e pegar todas as ajudas, caso seja enviado um id de usuário na rota /Help ele irá retornar todas as ajudas que não possuem esse usuário como dono 
[#31](https://github.com/mia-ajuda/Documentation/issues/31)
* Rota de criar ajuda
* Rota de pegar ajuda pelo id
* Rota para pegar todas as ajudas
> Us27 help list

- src/controllers/UserController.js
- src/models/Point.js
- src/models/User.js
- src/routes/UserRoutes.js
Foi alterado a model de usuário para receber um novo tipo de coordenada, o que facilita no momento de filtro por distância de ajuda. 
* Criação de um novo tipo, "point"
* Alteração da model de usuário
> Us12 share location

- .dockerignore
- docker-compose.yml
- src/config/database.js
- src/controllers/UserController.js
- src/models/Category.js
- src/models/Help.js
- src/models/Point.js
- src/models/Session.js
- src/models/User.js
- src/repository/BaseRepository.js
- src/repository/UserRepository.js
- src/routes/UserRoutes.js
- src/services/UserService.js
- src/utils/seed/HelpSeed.js
- src/utils/seed/UserSeed.js
Foi criado endpoints para criação , edição dos atributos , deleção logica e listagem das informações de usuário.
US06 e US08
> US06 & US08  editar e cadastrar usuário

- README.md
- package.json
- src/config/database.js
- src/models/User.js
- src/utils/seed/CategorySeed.js
- src/utils/seed/HelpSeed.js
- src/utils/seed/UserSeed.js
- yarn.lock
O atual _Pull Request_ evolui a aleatoriedade das seeds, além de adaptá-las às mudanças nos modelos.
> Melhorias na Seed após Atualizações nos Modelos

- src/controllers/HelpController.js
- src/repository/HelpRepository.js
- src/services/HelpService.js
Foi feito a parte de filtragem de pedidos por categoria, como descrito na historia.
[#32](https://github.com/mia-ajuda/Documentation/issues/32)
> US28 - Filtrar pedidos por categoria

- src/controllers/HelpController.js
- src/repository/BaseRepository.js
- src/repository/HelpRepository.js
- src/services/HelpService.js
O atual Pull Request implementa o limite de um usuário para 5 pedidos de ajuda.
[US20](https://github.com/mia-ajuda/Documentation/issues/23)
* Limita a 5 pedidos de ajuda por usuário
> US20: Cria limite para o número de pedidos de ajuda

- src/repository/BaseRepository.js
- src/services/CategoryService.js
- src/services/HelpService.js
- src/services/UserService.js
Foram corrigidas as mensagens e tratamentos de erro do sistema.
*  Altera lançamento de exceção da UserService;
*  Altera lançamento de exceção da HelpService;
*  Corrige lançamento de exceção na CategoryService.
> Correção lançamento de exceção

- src/utils/seed/HelpSeed.js
Foi removido o status deleted de CategorySeed.
* Removeu-se o status deleted do category seed
* Não ocorre mais problema  ao popular o banco
> HOTFIX:Remoção do status deleted na CategorySeed

- src/utils/seed/HelpSeed.js
- src/utils/seed/UserSeed.js
Agora a seed popula 100 usuários e ajudas
* A seed de user popula 100 usuários.
* A seed de help popula 100 ajudas.
* Trocou-se a geração de latitude e longitude.
* A latitude e longitude dos usuários são gerados em um range a partir da latitude e longitude de sua casa.
* Você deve trocar os números -15...latitude e -47... longitude para os de sua casa, para poder ver no mapa ajudas perto de você.
de sua casa.
> Evolução da seed

- src/controllers/UserController.js
- src/repository/UserRepository.js
- src/routes/UserRoutes.js
- src/services/UserService.js
Alterações no user para que ele só possa fazer alterações no próprio usuário, sem poder alterar dados de outros usuários;
Issue n foi criada :(
* Remoção de id nas rotas, com exceção do getUser
* Adição da rota checkUserExistence, que checa se um usuário existe por email ou cpf
* Movendo lógica de criar usuário no firebase da controller pra service
* Parametrizando a criação de um usuário no firebase para impedir conflitos quando um usuário for criado no front pelo gmail ou FB.
> Limitar edicoes ao próprio user

- src/controllers/HelpController.js
Foi consertado um erro nas rotas PUT.
* Foi alterado o envio de status de "res.status(204)" para "res.status(204).json()"
* O erro de não achar rotas Put foi consertado com essa mudança no envio de status.
> HOTFIX-Put Routes

- src/services/HelpService.js
- src/utils/NotificationMixin.js
Implementa notificação para o ajudado quando receber uma oferta de ajuda e notificações para todos os envolvidos quando uma ajuda for finalizada
[US25](https://github.com/mia-ajuda/Documentation/issues/28)
[US21](https://github.com/mia-ajuda/Documentation/issues/25)
* Implementar o método notify em conjunto com as mudanças de estado da ajuda
> Us21 notificar pedido de ajuda

- src/models/Help.js
- src/repository/BaseRepository.js
- src/repository/HelpRepository.js
- src/services/HelpService.js
Branch de HOTFIX para recuperar o nome da categoria relacionada com a ajuda.
[US22 - Ver pedidos em andamento](https://github.com/mia-ajuda/Documentation/issues/22)
branch | PR
US-22 Front | [US-22](https://github.com/mia-ajuda/Frontend/pull/16)
* Resgata as informações da categoria junto as informações da ajuda
> Ajuste da rota para pegar a lista de ajudas do usuário

- src/controllers/UserController.js
Foi consertado a rota de criação de usuário pelo firebase
- Cast para booleano da flag que determina se o cadastro é feito por redes sociais ou pelo cadastro convencional.
> Hotfix-Fixed signup with firebase

- src/repository/HelpRepository.js
- src/services/HelpService.js
- src/utils/seed/HelpSeed.js
Alterado a agregação para retornar apenas as ajudas waiting ou que o usuário é o helper.
[US-29](https://github.com/mia-ajuda/Documentation/issues/29)
* A agregação na helpHepository retorna agora as ajudas waiting e on_going na qual o usuário é o helper
* Ao escolher um usuário para ser o ajudante o status da ajuda muda para on_going
* A lista de possíveis ajudantes é limpa
> Us29 choose help

- src/config/database.js
- src/controllers/NotificationController.js
- src/models/Notification.js
- src/models/User.js
- src/repository/NotificationRepository.js
- src/routes/BaseRoutes.js
- src/routes/NotificationRoutes.js
- src/services/NotificationService.js
- src/utils/seed/NotificationSeed.js
Implementa o registro do histórico de notificações associadas a um determinado usuário.
[US51](https://github.com/mia-ajuda/Documentation/issues/51)
> WIP: Histórico de Notificações do Usuário

- src/repository/HelpRepository.js
- src/routes/UserRoutes.js
Pr com a ordenação de lista de ajudas perto ou não.
[#34](https://github.com/mia-ajuda/Documentation/issues/38) 
* Adicionadas agregações que listam e ordenam as ajudas, retornando também o usuário e a lista de categorias.
* O retorno do usuário (ownerId) da ajuda bem num objeto __user__, e não mais num array de objetos com um único item.
> Sort HelpList

- src/repository/HelpRepository.js
Adicionando mais um passo à agregação de listagem de ajudas para detalhar os possibleHelpers
--
* Adicionando o passo lookup nos possibleHelpers
> Adding lookup to get possibleHelpers user info

- src/models/Help.js
- src/repository/NotificationRepository.js
- src/routes/NotificationRoutes.js
- src/services/HelpService.js
- src/services/NotificationService.js
- src/utils/schedule.js
Implementa o registro do histórico de notificações associadas a um determinado usuário.
[US51](https://github.com/mia-ajuda/Documentation/issues/51)
> US51: Salvar Notificações na Base de Dados (PR 2)

- src/repository/HelpRepository.js
- src/services/HelpService.js
Conserta-se o erro no qual o usuário dentro de uma ajuda vinha como array quando a ajuda era criada pelo socket
* O usuário retorna como objeto dentro da criação de uma ajuda.
> HOTFIX-SocketError

- src/services/HelpService.js
Ajustado erro na chamada do método do método de enviar notificações e substituição por console.logs nos erros de notificação para evitar que pare a execução
> Hotfix - Notificação

- src/services/HelpService.js
Um usuário ao escolher um helper para sua ajuda, esta ajuda desaparece para os outros usuários.
* Usuário escolhe um ajudante, ajuda some do mapa para todos.
* Trata-se o erro no caso de um usuário diferente do escolhido para ser ajudante estivesse dentro da página de descrição de ajuda e clicasse em oferecer ajuda.
> Socket helper

- src/services/UserService.js
os emails na hora do cadastro estavam sendo salvos com letra maiúscula no mongo e com letra minpuscula no firebase na hora da criação
[#58](https://github.com/mia-ajuda/Documentation/issues/58)
* garantir que o email seja salvo em minúsculo no mongo e firebase
> Hotfix-Emails With Uppercase

- index.js
Prepara o backend para receber arquivos no formato de base64
#59 Implementar Persistência da Imagem de Perfil do Usuário #59
* Aumento da capacidade de arquivo que o express pode receber
> Addição de imagem em base64 no backend

- src/services/HelpService.js
O ajudante agora também recebe notificação quando a ajuda termina.
* Ajudante recebe notificação quando a ajuda muda para status "finished"
* Consertou-se o erro no qual a notificação "Sua oferta de ajuda foi aceita" não era salva no banco de dados.
> Hotfix-notications

- docker-compose.yml
- package.json
- src/controllers/HelpController.js
- src/repository/HelpRepository.js
- src/routes/HelpRoutes.js
- src/services/HelpService.js
Adição do endpoint de obtenção de lista de ajudas por ownerId e status
[#73](https://github.com/mia-ajuda/Documentation/issues/73)
branch | PR
Enhancement-requestUserHelpbyStatus | [Enhancement-requestUserHelpbyStatus](https://github.com/mia-ajuda/Frontend/pull/39)
* Adição das rotas, controller, service e repository
Este pull request só deve ser aceito caso [Enhancement-requestUserHelpbyStatus](https://github.com/mia-ajuda/Frontend/pull/39) vá ser aceito junto.
> Adding get help list by status

- .gitlab-ci.yml
- Dockerfile
- docker-compose.yml
Criação do CI e configuração do Deploy automático
#50 Publicar o Backend
* Criar CI da aplicação
* Configurar Máquinas
* Criar stage de Deploy
* Configurar Watchtower para detecção de mudanças na imagem
> Configuracao ci

- src/repository/HelpRepository.js
- src/services/HelpService.js
Foi alterado a requisição da ajuda por status para procurar também ajudas no qual o usuário é possível ajudante.
branch | PR
Hotfix-MeusPedidos| [Hotfix-meusPedidos](https://github.com/mia-ajuda/Frontend/pull/49)
* Foi alterado a requisição de ajuda por status para procurar ajudas no qual o usuário é possível ajudante. 
Esse pr deve ser aceito junto com o pr [Hotfix-meusPedidos](https://github.com/mia-ajuda/Frontend/pull/49) do front-end.
> Hotfix-MeusPedidos

- src/repository/HelpRepository.js
- src/services/HelpService.js
- websocket.js
Foram feitas alterações para que todas as ajudas sejam carregadas no mapa quando o usuário entrar no aplicativo, em vez de mostrar ajudas em um raio de 2 km.
[108](https://github.com/mia-ajuda/Documentation/issues/108)
repositório | branch | PR
------ | ------ | ------
Front-end | 108-AjusteMapa | [108-AjusteMapa](https://github.com/mia-ajuda/Frontend/pull/74)
* Ordena ajudas apenas pela distância.
* Foi removido a passagem de distância para o socket pela HelpService.
* Remove filtro por distância no socket.
* Insere distanceValue em ajudas que chegam no front pelo socket.
> 108-AjusteMapa

- websocket.js
Consertado o erro ao escolher um ajudante.
* Calcula-se a distância apenas em ajudas que foram criadas.
> Hotfix-Socket

- .gitignore
- .gitlab-ci.yml
- README.md
- src/config/authFirebase.js
Este __pull request__ unifica os arquivos de configuração do firebase a fim de evitar o armazenamento local de arquivos de configuração de produção.
> [HOTFIX] Unificação dos arquivos de configuração do firebase

- src/controllers/EntityController.js
- src/controllers/UserController.js
- src/models/Entity.js
- src/repository/EntityRepository.js
- src/routes/BaseRoutes.js
- src/routes/EntityRoutes.js
- src/routes/UserRoutes.js
- src/services/EntityService.js
- src/services/UserService.js
Com as novas funcionalidades implementadas nesse _pull request_, será possível realizar o cadastro e a edição de informações de perfil de ONGs na plataforma Mia Ajuda, além de abrir a possibilidade de escolher fotos da galeria durante o cadastro de ONGs.
O presente _pull request_ soluciona três issues: [US48](https://github.com/mia-ajuda/Documentation/issues/128), [US49](https://github.com/mia-ajuda/Documentation/issues/129), [US50](https://github.com/mia-ajuda/Documentation/issues/130).
> [FEATURE] Fluxo de Cadastro e Edição de Perfil de ONGs

- src/services/EntityService.js
- src/services/HelpService.js
- src/services/UserService.js
Esse pr adiciona uma informação a mais no cadastro de usuário para informar o seu tipo, isso ajuda o front end a recuperar o usuário de forma mais ágil sem requisições no banco para descobrir o tipo de usuário.
> [Enchancement] User request

- src/controllers/HelpController.js
- src/repository/BaseRepository.js
- src/repository/HelpRepository.js
- src/routes/HelpRoutes.js
- src/services/HelpService.js
- websocket.js
Cria as rotas que devolvem apenas as informações necessárias para o front-end em vez de tudo.
[115](https://github.com/mia-ajuda/Documentation/issues/115)
Repositório| branch | PR
------ | ------ | ------
Front-end | 115-ChangeHelpListRequest | [115-change help list request](https://github.com/mia-ajuda/Frontend/pull/108)
* Transforma getNearHelp em shortList
* Cria getHelpInfo que retorna apenas as informações necessárias para o front-end.
A issue [115](https://github.com/mia-ajuda/Documentation/issues/115) não está completa pois ainda há outras requisições que possuem informações demais, foi feito esse pr para dividir a tarefa em partes.  Aceitar esse pr apenas se [115-change help list request](https://github.com/mia-ajuda/Frontend/pull/108) também for ser aceito junto.
> 115 change help list request

- src/repository/HelpOfferRepository.js
- src/repository/HelpRepository.js
Esse pr implementa a lógica para listar as ofertas de ajuda
[#117](https://github.com/mia-ajuda/Documentation/issues/117)
* Adição da lógica para listar as ofertas de ajuda no mapa 
* Adição da lógica de otimização de dados, para que informações como photo e endereço que são desnecessários para listagem não sejam retornardos na requisião
*Adaptação do request na página de descrição da ajuda para puxar os dados do criador da ajuda e mostrar seus detalhes na página de descrição.
> Fix problem to return possiblehelpoers for a help

- src/controllers/HelpOfferController.js
- src/services/HelpOfferService.js
As ofertas de ajuda estavam sendo retornadas ao proprio usuário que as criou, esse pr conserta isso
* Adição da excessão para não retornar a propria oferta de ajuda
> Fix the bug to return my own helpoffer

- src/controllers/HelpController.js
- src/repository/HelpRepository.js
- src/services/HelpService.js
Esse __pull request__ tem por objetivo reduzir a quantidade de informações trafegadas do backend para o frontend.
[US115](https://github.com/mia-ajuda/Documentation/issues/115)
Repositório | branch | PR
------ | ------ | ------
Frontend | 115-Part2 | [PR](https://github.com/mia-ajuda/Frontend/pull/114)
> [US115] Refatoração da quantidade de dados retornados ao frontend

- src/controllers/HelpOfferController.js
- src/repository/HelpOfferRepository.js
- src/services/HelpOfferService.js
- src/utils/seed/HelpSeed.js
Adequação da rota de de listar ofertas para ter um filtro de categorias.
[#122](https://github.com/mia-ajuda/Documentation/issues/122)
[#118](https://github.com/mia-ajuda/Frontend/pull/118)
>  US42 - New map filter

- src/controllers/HelpController.js
- src/repository/HelpRepository.js
- src/routes/HelpRoutes.js
Remoção de rotas que não estavam sendo utilizadas e redução de atributos enviados ao front.
[US115](https://github.com/mia-ajuda/Documentation/issues/115)
Repositório | branch | PR
------ | ------ | ------
Frontend| 115-Part3_TheEnemyReturns | [PR](https://github.com/mia-ajuda/Frontend/pull/120)
*  Remoção das rotas getHelpById,
*  Inserção do project em getByIdWithAggregation,
*  Refatoração da getHelpListByStatus
Esse pr deve ser aceito com o [PR]( https://github.com/mia-ajuda/Frontend/pull/120) do Frontend.
> 115-Part3: Diminuição dos dados retornados ao Frontend

- src/config/database.js
- src/controllers/HelpOfferController.js
- src/repository/BaseRepository.js
- src/repository/HelpOfferRepository.js
- src/routes/HelpOfferRoutes.js
- src/services/HelpOfferService.js
Foi criado a rota de deleção lógica de uma oferta de ajuda.
[US43](https://github.com/mia-ajuda/Documentation/issues/123)
*  Cria rota para deleção lógica de uma oferta de ajuda
*  Valida se o usuário que está deletando a oferta de ajuda é o dono.
> Us43-delete help offer

- src/controllers/CampaignController.js
- src/controllers/HelpOfferController.js
- src/repository/HelpOfferRepository.js
- src/routes/HelpOfferRoutes.js
Rota corrigida para listar ofertas de ajuda
Não sei qual issue resolve :P
[PR-125](https://github.com/mia-ajuda/Frontend/pull/125/)
> Listar Ofertas de Ajuda

- src/controllers/CampaignController.js
- src/routes/CampaignRoutes.js
- src/services/CampaignService.js
Criação de uma rota para pegar as informações da campanha pelo id.
#163
Tela individual campanha | Frontend
* Criação da rota de campanha pelo id.
> Criação de rota de informações individuais sobre campanha

- src/controllers/CampaignController.js
- src/routes/CampaignRoutes.js
- src/services/CampaignService.js
Agora a ONG pode finalizar uma campanha quando for necessario
Issues que foram resolvidas com o PR
[#138](https://github.com/mia-ajuda/Frontend/pull/138)
> US57 - Agora a ONG pode finalizar uma campanha quando for necessario

- src/controllers/HelpController.js
- src/controllers/HelpOfferController.js
- src/models/Notification.js
- src/repository/HelpOfferRepository.js
- src/repository/HelpRepository.js
- src/routes/HelpOfferRoutes.js
- src/routes/HelpRoutes.js
- src/services/HelpOfferService.js
- src/services/HelpService.js
- src/utils/sharedAggregationInfo.js
Esse PR adiciona uma nova rota para pegar as informações de uma oferta de ajuda necessárias na página de oferta.
Essa rota é necessária para solucionar o bug de notificação de oferta crashando o app ao ser clicada
[171](https://github.com/mia-ajuda/Documentation/issues/171)
branch | PR
outro_pr_relacionado | [link]()
* Criação de nova rota, controller, service e repository
> Bug das notificações de oferta de ajuda

- CONTRIBUTING.md
- package.json
Foi adicionado o novo guia de contribuição do projeto. Além da adição do _commit lint_
* Adição do documento CONTRIBUTING.md
* Adição do _commit lint_
> Solve - Updating Contributing Guide

- src/models/Campaign.js
- src/models/Help.js
- src/models/HelpOffer.js
- src/repository/BaseRepository.js
- src/repository/CampaignRepository.js
- src/repository/HelpOfferRepository.js
- src/repository/HelpRepository.js
- src/utils/sharedAggregationInfo.js
Refatorando as agregações no repository utilizando o método populate.
- https://github.com/mia-ajuda/Documentation/issues/174
* Substitui o método listAgreggate por populate
> 174-refactoring aggregations

- src/controllers/HelpOfferController.js
- src/models/HelpOffer.js
- src/models/Notification.js
- src/repository/HelpOfferRepository.js
- src/routes/HelpOfferRoutes.js
- src/services/HelpOfferService.js
Co-authored-by: Damaso Junio <junio.pereirab@gmail.com>
Será adicionado os métodos e rotas  que vão tratar da adição de pessoas necessitadas no array de pessoas necessitadas, bem como a retirada dessas pessoas que foram escolhidas do array de possíveis pessoas, e também configurada a notificação para a pessoa que foi aceita.
[#125](https://github.com/mia-ajuda/Documentation/issues/125)
branch | PR
US45 - Aceitação de pessoas interessadas para ajudar | [mia-ajuda/Frontend](https://github.com/mia-ajuda/Frontend/pull/168)
* Adicionado métodos e rota para alteração dos arrays de possibleHelpedUsers e helpedUsers
* Configurado a notificação para o necessitado que foi aceito na oferta
> US45 - Aceitação de pessoas interessadas para ajudar

- src/repository/HelpOfferRepository.js
- src/services/HelpOfferService.js
A notificação, pelo socket, da deleção da oferta de ajuda foi implementada.
- https://github.com/mia-ajuda/Documentation/issues/123
- Crie uma oferta
- Entre em uma conta diferente
- Localize a oferta
- Exclua a oferta enquanto visualiza de uma conta diferente da dona.
- A oferta some sem precisar atualizar o mapa
branch | PR
US43-delete_help_offer_socket |  https://github.com/mia-ajuda/Frontend/pull/165
- Notifica, pelo socket, o frontend quando uma oferta de ajuda for apagada
> US43: Deletando Oferta de Ajuda e Notificando pelo Socket

- src/repository/HelpRepository.js
Adição do field "creationDate" na requisição que retorna a lista de ofertas e pedidos
[209](https://github.com/mia-ajuda/Documentation/issues/209)
branch | PR
209-ShowOfferDate | [Frontend 209](https://github.com/mia-ajuda/Frontend/pull/194)
* Adição do field "creationDate" na requisição que retorna a lista de ofertas e pedidos
> 209-Mostrar data de criação de pedido, oferta e campanha

- src/controllers/EntityController.js
- src/controllers/UserController.js
- src/models/Entity.js
- src/models/User.js
- src/services/EntityService.js
- src/services/UserService.js
Remoção da obrigatoriedade de alguns campos a fim de diminuir o fluxo de cadastrado
[205 - Refatoração do Fluxo de Registro no APP](https://github.com/mia-ajuda/Documentation/issues/205)
branch | PR
205-RefactorRegister | [205 - Refatorar Registro](https://github.com/mia-ajuda/Frontend/pull/198)
* Remoção de obrigatoriedade nos campos que não são pedidos quando usuário cria a conta;
* Adição do endereço quando no endpoint de edição de conta.
> 205 - Refatorar Registro

- src/utils/seed/HelpOfferCampaignSeed.js
- src/utils/seed/mockedInfos/mockedHelpInfo.js
- src/utils/seed/mockedInfos/mockedOfferInfo.js
- yarn.lock
Alteração na lógica do sedes para mostrar títulos e descrições em PT-br.
* Criação de títulos e descrições mocadas;
* Utilização dos mocks no arquivo de feeds.
> Change title and description in seeds to pt-br

- src/controllers/SocialNetworkProfileController.js
- src/models/User.js
- src/repository/SocialNetworkRepository.js
- src/routes/SocialNetworkRoutes.js
Atualizações no backend para melhorar lógica de busca de usuários.
[222](https://github.com/mia-ajuda/Documentation/issues/222)
branch | PR
222-FollowUsersFlow | [Frontend #223](https://github.com/mia-ajuda/Frontend/pull/223)
* Adição do index no nome do usuário;
* Alteração no parametro da rota de pesquisas para query, afim de retornar a lista de todos os usuários quando o nome for vazio.
> 222 - Eu, como usuário, desejo poder seguir outras pessoas no aplicativo, para que eu possa acessar seus perfis de maneira rápida

- src/repository/HelpOfferRepository.js
Altera os campos em comum em alguns modelos de dados que são recuperados posteriormente no backend.
[Refatoração da Tela de detalhes das Minhas Ofertas](https://github.com/mia-ajuda/Documentation/issues/220)
branch | PR
Refatoração da tela de detalhes das Minhas Ofertas | [link](https://github.com/mia-ajuda/Frontend/pull/217)
* Alteração no envio de modelos de dados em comum
> Passa campos em comum para alguns modelos de dados envolvendo usuários

- src/controllers/EntityController.js
- src/controllers/UserController.js
- src/models/Entity.js
- src/models/User.js
- src/repository/BaseRepository.js
- src/repository/CampaignRepository.js
- src/repository/SocialNetworkRepository.js
- src/services/EntityService.js
- src/services/SocialNetworkService.js
- src/services/UserService.js
- src/utils/mapSocialNetworkUser.js
Adição de novo campo e retorno de campanhas para o perfil.
[US16 - Eu, como usuário, desejo editar os dados do meu perfil em uma única tela para que a edição fique mais simples](https://github.com/mia-ajuda/Documentation/issues/238)
branch | PR
238-EditProfile | [227](https://github.com/mia-ajuda/Frontend/pull/227)
* Adição do campo biography na model user e entity;
* Adição do campo na lógica de edição de dados;
* Retorna dados da campanha no perfil do usuário;
* Altera o get by id para receber um objeto para popular os dados.
> Alterações para Perfil de Usuário

- src/controllers/BadgeController.js
- src/repository/BadgeRepository.js
- src/services/BadgeService.js
- src/utils/seed/HelpOfferCampaignSeed.js
- src/utils/seed/mockedInfos/mockedBadgesInfo.js
Criação da lógica para popular dados do badge template.
[US03 - Eu, como usuário ajudante, desejo ter um reconhecimento quando criar uma oferta ou oferecer ajuda a um pedido no aplicativo, para que eu possa me sentir bem sempre que entrar no aplicativo](https://github.com/mia-ajuda/Documentation/issues/225)
branch | PR
225-OfferBadge | [US03 - Eu, como usuário ajudante, desejo ter um reconhecimento quando criar uma oferta ou oferecer ajuda a um pedido no aplicativo, para que eu possa me sentir bem sempre que entrar no aplicativo](https://github.com/mia-ajuda/Frontend/pull/229)
* Criação da lógica de mostrar que a badge subiu de nível recentemente;
* Criação da lógica de popular dados das badges;
* Atualização nos seeds de ajuda, oferta, campanhas e badges.
> Alteração na lógica de badges

- src/repository/HelpRepository.js
Adição do campo creationDate no helprepository.
[US13 - Eu, como usuário, desejo encontrar pedidos e ofertas com a marcação de novo pedido no mapa para interagir com aquele pedido](https://github.com/mia-ajuda/Documentation/issues/233)
branch | PR
232-NewActivityMarkerAndCard | [232](https://github.com/mia-ajuda/Frontend/pull/232)
* Adição do campo creationDate no helprepository
> Retorna creation date para pedido

- src/repository/HelpRepository.js
Adiciona a sigla do estado do endereço do usuário na API de ajuda
branch | PR
239-RefactorMyRequestScreen | [link](https://github.com/mia-ajuda/Frontend/pull/233)
* Adiciona a sigla do estado do endereço do usuário na API de ajuda
> Adiciona a sigla do estado do endereço do usuário na API de ajuda

- src/controllers/FeedbackController.js
- src/models/Feedback.js
- src/repository/FeedbackRepository.js
- src/routes/BaseRoutes.js
- src/routes/FeedbackRoutes.js
- src/services/FeedbackService.js
Criação de toda estrutura de envio de feedbacks para outros usuários no backend.
[US11 - Eu, como usuário ajudado, desejo poder deixar feedback para um usuário ajudante que me ajudou em algum pedido para demonstrar meu agradecimento](https://github.com/mia-ajuda/Documentation/issues/231)
branch | PR
231-FeedbackFlow | [Fluxo de Feedback](https://github.com/mia-ajuda/Frontend/pull/240)
* Criação de model de feedback;
* Criação de repository, service e controller para envio de feedbacks;
* Criação de repository, service e controller para listagem de feedbacks.
> Estrutura de Feedback

- src/controllers/ActivityController.js
- src/controllers/HelpOfferController.js
- src/models/HelpOffer.js
- src/repository/CampaignRepository.js
- src/repository/HelpOfferRepository.js
- src/repository/HelpRepository.js
- src/routes/ActivityRoutes.js
- src/routes/BaseRoutes.js
- src/services/ActivityService.js
- src/services/HelpOfferService.js
- src/services/SocialNetworkService.js
- src/utils/addHelpTypeToList.js
- src/utils/sortActivitiesByDistance.js
Criação da API de Atividades
branch | PR
feat/create-activity-logic | https://github.com/mia-ajuda/Frontend/pull/247
* Criação da API de Atividades
> Criação da API de Atividades

- src/config/database.js
- src/controllers/FeedbackController.js
- src/controllers/HelpController.js
- src/controllers/HelpOfferController.js
- src/controllers/TimelineEventController.js
- src/controllers/UserController.js
- src/models/TimelineEvent.js
- src/models/TimelineEventTemplate.js
- src/repository/TimelineEventRepository.js
- src/routes/BaseRoutes.js
- src/routes/TimelineEventRoutes.js
- src/services/HelpService.js
- src/services/TimelineEventService.js
- src/utils/enums/timelineEnum.js
- src/utils/seed/TimelineEventTemplateSeed.js
- src/utils/seed/mockedInfos/mockedTimelineEventTemplatesInfo.js
Criação de eventos que estarão na linha do tempo do usuário.
[US08 - Eu, como usuário do aplicativo Mia Ajuda, desejo ter uma linha do tempo com o resumo das minhas principais interações do aplicativo para que eu possa relembrar tudo que já passei dentro do aplicativo](https://github.com/mia-ajuda/Documentation/issues/236)
branch | PR
236-Timeline | [236 - Criação de tela de linha do tempo](https://github.com/mia-ajuda/Frontend/pull/246)
* Criação de toda estrutura de linha do tempo;
* Criação de lógicas para adicionar o evento em determinadas ações.
> 236 - Criação de eventos da linha do tempo do usuário

- src/models/Campaign.js
- src/models/Help.js
- src/models/HelpOffer.js
- src/repository/CampaignRepository.js
- src/repository/HelpOfferRepository.js
- src/repository/HelpRepository.js
- src/services/SocialNetworkService.js
- src/utils/addHelpTypeToList.js
- src/utils/seed/HelpOfferCampaignSeed.js
- src/utils/seed/addIndexToOldActivities.js
A tela de minhas ofertas estava quebrando pois existia um lugar no código do backend onde era realizado um loop em uma lista de ofertas utilizando o spread(...) em cada uma delas, porém estas ofertas não eram transformadas em object antes de realizar essa operação.
Inicialmente a primeira solução (commit 1) foi apenas rodar o método citado dentro do bloco de código que realizava o tratamento utilizando o toObject. Depois foi observado que, como a ideia da função era adicionar a mesma string para todos os elementos de uma mesma model fazia mais sentido utilizar um virtual para isso, para evitar um loop que no futuro poderia gastar tempo.
> HOTFIX - Tela de minhas ofertas quebrando

- src/repository/SocialNetworkRepository.js
Retorna a lista de usuários limitada.
* Usa o limit para limitar a função para retornar apenas 20 usuários.
> HOTFIX - Tela de pesquisa de usuário
