- src/controllers/HelpController.js
- src/repository/HelpRepository.js
- src/services/HelpService.js
Foram feitas mudanças nas queries da rota /help
* adicionar campo id.except, faz com que a query ajudas de todos os donos menos o com id passado
* adicionado campo id.helper, se passado a query fará a busca no banco procurando o id passado como helper id
* Além disso essa mesma rota procura por status caso passado na query
> change rules for querying helps

- src/utils/NotificationMixin.js
Troca o warning de erro por um console log, quando a notificação falhar por falta de deviceId.
[54](https://github.com/mia-ajuda/Documentation/issues/54)
> Removing notification warning

- src/repository/HelpRepository.js
O listNear retorna apenas ajudas com status waiting.
* Foi alterado o matchQuery na listNear dentro da HelpRepository para procurar apenas ajudas com status wainting.
* No front-end a parte de "minhas ofertas de ajuda" não precisa mais que o listNear retorne ajudas com status on_going.
> HOTFIX-ListNear

- src/services/HelpService.js
Verifica-se a situação de inserção de id de categoria inválido.
* Caso seja criado uma ajuda com id de categoria inválido retorna erro.
* Esse erro não ocorre no front pois é provido uma lista de categorias na criação de uma ajuda, porém é de minha opinião que é necessário tratar esse erro de requisição.
> Hotfix-ValidationCategoryIdHelpService

- Dockerfile
- docs/swagger.yaml
- package.json
- src/controllers/UserController.js
- src/routes/BaseRoutes.js
- yarn.lock
O atual _Pull Request_ adiciona a documentação dos endpoints do backend através do `swagger.io`.
Para utilizar o swagger, prossiga com os passos abaixo:
1. Suba o backend através do comando `sudo docker-compose up --build`;
2. Acesse o swagger pelo navegador: `http://localhost:8000/api-docs/`;
3. Utilize a interface do swagger para verificar os formatos de _request_ e _response_ das rotas e realizar requisições.
* Observação: caso a rota a ser explorada necessite de autenticação, obtenha o token e preencha-o no campo "_Authorize_".
Não há issues ou histórias de usuário relacionadas a esse _pull request_.
> Documentação de Endpoints do Backend com Swagger

- src/repository/HelpRepository.js
- src/services/HelpService.js
Havia um erro no limite de ajudas, no qual ajudas com status finished também eram contabilizadas,
assim o usuário poderia ter no máximo 5 ajudas contanto com ajudas finalizadas e não finalizadas.
* Agora o countDocuments só conta ajudas com status diferente de finished, como "on_going","waiting","owner_finished","helper_finished".
* Este pull request deve ser aceito após o pull request do Hotfix-notifications.
> Hotfix-LimiteAjudas

- src/services/HelpService.js
O ajudante agora também recebe notificação quando a ajuda termina.
* Ajudante recebe notificação quando a ajuda muda para status "finished"
* Consertou-se o erro no qual a notificação "Sua oferta de ajuda foi aceita" não era salva no banco de dados.
Esse pr refaz o que foi feito em um pr anterior [Hotfix-notifications](https://github.com/mia-ajuda/Backend/pull/49), porém como foi apagado por um erro teve que ser refeito.
> Redo notifications

- websocket.js
Havia um bug no qual quando o usuário A estava com o filtro ligado(filtrou para ver apenas ajudas de higiene pessoal por exemplo), se uma ajuda fosse criada por outro usuário B com a mesma categoria que o usuário A filtrou, esssa ajuda não aparecia no mapa do usuário A. Havia um problema com comparação de tipos que foi resolvida. Agora este problema não ocorre mais.
* Troca-se o includes por um for.
> Hotfix-categorySocket

- .gitlab-ci.yml
Hotfix para incluir a variável de ambiente do firebase de dev no CI de produção
* Adição da variável de ambiente de dev para o firebase e script para recuperar o arquivo de dev para o projeto.
> Adding firebase dev to the ci

- .gitignore
- .gitlab-ci.yml
- README.md
- config/backup-scheduler.yaml
- docker-compose.prod.yml
Com o incremento do atual pull request, haverá um serviço na aplicação que realizará backups da base de dados `miaAjudaDB` regularmente às 04h da manhã. O serviço guardará um total de 14 backups locais e sempre salvará o backup no Google Drive de desenvolvimento do projeto (credenciais no drive principal).
[US100](https://github.com/mia-ajuda/Documentation/issues/100)
> [US100] Rotina para Backup da Base de Dados

- src/repository/HelpRepository.js
- src/services/HelpService.js
Foi criado as páginas e lógicas para a adição de mais de uma categoria em uma oferta/pedido de ajuda. Agora, pode-se criar mais de uma categoria para uma ajuda; Limite de 3 categorias;
[#118](https://github.com/mia-ajuda/Documentation/issues/118) - Categorizar ofertas
branch | PR
118-helpCategory (Frontend) | [#110](https://github.com/mia-ajuda/Frontend/pull/110)
* Troca no schema de oferta de ajuda e ajuda para receber mais de uma categoria 
Teste: 
- Suba o backend na branch 118-HelpCategory;
- No frontend use a brach 118-HelpCategory, crie uma oferta de ajuda e uma ajuda. Selecione mais de uma categoria;
- No app, na página de meus pedidos, verifique se sua ajuda foi criada e se possui mais de uma categoria;
- Obs, testar, também o filtro por categoria no mapa;
> [Feature] Help Categories

- index.js
Foi comentado o cron que verifica se uma ajuda é antiga e deleta ela, assim as ajudas vão ficar no mapa indefinitivamente
[#161](https://github.com/mia-ajuda/Documentation/issues/161)
* Comentar cron
> Retirar validade da ajuda

- src/controllers/HelpOfferController.js
- src/routes/HelpOfferRoutes.js
- Foi arrumada a rota para retorna somente as ofertas de ajuda do próprio usuário. 
- E esse PR deve ser aceito **junto** com o [44-history](https://github.com/mia-ajuda/Frontend/pull/123)
> [HotFix] - Rota para retornar somente próprias ajudas

- src/services/HelpService.js
Agora campanhas conseguem se candidatar para uma ajuda. Isso não ocorria anteriormente por um erro.
[172](https://github.com/mia-ajuda/Documentation/issues/172)
* Apaga o local que definia o tipo de usuário como normal onde o usuário era uma OnG
> Fix error when setting userType

- src/repository/HelpOfferRepository.js
- src/routes/HelpOfferRoutes.js
Co-authored-by: Thiago Paiva <thiagohdaqw@gmail.com>
Foi realizada a listagem de pessoas interessadas em ofertas de ajuda de acordo com a issue [#124](https://github.com/mia-ajuda/Documentation/issues/124). Os métodos e as rotas já estavam construídas, foi apenas uma mudança feita nas agregações do helpOfferRepository para possibilitar a devolução dos dados das pessoas que desejam ser ajudadas pela oferta de ajuda.
[#124](https://github.com/mia-ajuda/Documentation/issues/124)
* Alteração nas agregações do helpOfferRepository
> US44 - Listagem de pessoas interessadas

- src/repository/HelpRepository.js
O dono da ajuda não conseguia ver as ongs que tentavam lhe ajudar. O que tava acontecendo era que faltava o `$lookup` para recuperar os `possibleEntities` do banco de dados.
- https://github.com/mia-ajuda/Documentation/issues/189
- Crie uma ajuda.
- Com uma conta de organização, se ofereça a ajudar.
- Veja se a organização aparece na lista de possiveis ajudantes da ajuda.
* A ajuda foi populada com os `possibleEntities`
> HOTFIX - Listagem de ongs como possíveis ajudantes.

- src/controllers/HelpController.js
- src/controllers/HelpOfferController.js
- src/repository/HelpOfferRepository.js
- src/repository/HelpRepository.js
- src/services/HelpOfferService.js
- src/services/HelpService.js
Antes, as ajudas/ofertas eram retornadas sem filtrar se a instituição já foi candidatado. Agora, está ocorrendo esse filtro.
1.  Entre com uma conta de instituição
2. Se candidate para varias ofertas/ajudas.
3. Dê o reload ou reentre na aplicação.
4. Note que as ofertas/ajudas já candidatadas não são mostradas no mapa.
- https://github.com/mia-ajuda/Documentation/issues/202
* Adição do filtro de instituição já candidatada
> Hotfix - Filtro de ajuda/oferta da Instituição já candidatada

- src/services/HelpService.js
Resolve bug no qual disparava erro ao comparar o owner id do pedido com a owner id enviado na request.  
[Abrir whatsapp para pedidos e ofertas #214](https://github.com/mia-ajuda/Documentation/issues/214)
branch | PR
214-OpenWhatsappForRequests | [214 - Abrir whatsapp para pedidos](https://github.com/mia-ajuda/Frontend/pull/204)
* Adicionar método to string no object id retornado pelo mongo.
> 214 - Abrir whatsapp para pedidos

- websocket.js
Um bug estava ocorrendo pois a função tentava pegar a localização do usuário sendo que em pedidos novos é para utilizar a localização do pedido em si.
* Ao invés de passar a localização do usuário passar a função que, caso o pedido tenha localização própria irá utilizar ela.
> HOTFIX: get position from the right place

- src/services/SocialNetworkService.js
O endpoint estava quebrando por falta do parâmetro se era ou não entidade.
* Adição do parâmetro isEntity=false que estava faltando na lógica da rede social
> chore: add missing parameter

- src/repository/SocialNetworkRepository.js
Limita o número máximo de usuários que serão retornados na busca, futuramente será implementado uma paginação.
-
* Cria lógica para limitar o número de usuários retornado pela query.
> chore: limit user find by name
